(function () {
  var script = document.currentScript;
  var base = (script && script.getAttribute('data-base')) || '.';
  var html = ''
    + '<footer id="contact">'
    + '  <div class="footer-grid">'
    + '    <div>'
    + '      <h4>Raven &amp; Ridge Outfitters</h4>'
    + '      <p>412 Timberline Way<br>Corvid Hollow, CO 80000</p>'
    + '    </div>'
    + '    <div>'
    + '      <h4>Contact</h4>'
    + '      <a href="mailto:hello@ravenandridge.example">hello@ravenandridge.example</a>'
    + '      <a href="mailto:wholesale@ravenandridge.example">wholesale@ravenandridge.example</a>'
    + '      <a href="#">+1 (555) 019-2847</a>'
    + '    </div>'
    + '    <div>'
    + '      <h4>Shop</h4>'
    + '      <a href="' + base + '/index.html#shop">Packs &amp; Shelters</a>'
    + '      <a href="' + base + '/offerings.html">Membership</a>'
    + '      <a href="' + base + '/locations.html">Stockists</a>'
    + '    </div>'
    + '    <div>'
    + '      <h4>Follow</h4>'
    + '      <a href="#">Instagram</a>'
    + '      <a href="' + base + '/journal.html">Trail Journal</a>'
    + '    </div>'
    + '    <div>'
    + '      <h4>Legal</h4>'
    + '      <a href="' + base + '/policies.html">Policies</a>'
    + '      <a href="' + base + '/faq.html">FAQ</a>'
    + '    </div>'
    + '  </div>'
    + '  <div class="footer-bottom">'
    + '    &copy; 2026 Raven &amp; Ridge Outfitters. All rights reserved.'
    + '  </div>'
    + '</footer>';
  document.write(html);
})();
